### ISSUE TITLE
Replace imp by importlib package

### ISSUE THREAD

**Issue by pradal** [openalea/core#21]
core/src/openalea/core/package.py:44: DeprecationWarning: the imp module is deprecated in favour     of importlib; see the module's documentation for alternative uses
    import imp

In the method register_package use importlib rather than imp

**Comment by pradal** [comment]
There is yet an issue.
When creating a package, the nodemodule is "mynode".
The import can fail.
We need to rethink the import system or to write "MyPackage.mynode' for the import.
This is due to the absolute import that change in Python3

**Comment by baugetfa** [comment]
fixed with commit 11fc2dd61d4099b71b743f4e2444c04ea9bc957d
