### ISSUE TITLE
in core there are several imports from `openalea.visualea`

### ISSUE THREAD

**Issue by baugetfa** [openalea/core#26]
Should we have `from openalea.visualea` in core. They appear in instantiate functions in:

- `src/openalea/core/node.py`, twice
- `src/openalea/core/compositenode.py`, twice
- `src/openalea/core/data.py`, once

Should not be a problem, because those lines should be called only when using graphical interface, I guess, so when we use `visualea`.

**Comment by pradal** [comment]
Core do not depends on VisuAlea. This is always specific cases where we ask a node to instantiate a widgets.
These methods are called from visualea. So no problem.
